[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.build]
cmds = ["cd backoffice-api && npm install", "cd backoffice-api && npm run build"]

[start]
cmd = "cd backoffice-api && npm run start:prod"

[variables]
NODE_ENV = "production"
PORT = "3000"